#docker-compose.yml
version: "3.0"
services:
  app:
    network_mode: host
    build: .
    volumes:
      - .:/app
    environment:
      DB_USER: postgres
      DB_HOST: santa
      DB_PASSWORD: Rjkzy231240
    restart: always
